// File auto-generated by flutterfire_cli. Edit at your own risk.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (const bool.fromEnvironment('dart.library.js')) {
      return web;
    }
    switch (const String.fromEnvironment('platform')) {
      case 'android':
        return android;
      case 'ios':
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBROrJliuIDbOHbsFSc8hhCrbkNYavLfxE',
    appId: '1:511982273812:android:08d6bdf203bd8284386e01',
    messagingSenderId: '511982273812',
    projectId: 'smarttask-baff9',
    storageBucket: 'smarttask-baff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBROrJliuIDbOHbsFSc8hhCrbkNYavLfxE',
    appId: '1:511982273812:ios:08d6bdf203bd8284386e01',
    messagingSenderId: '511982273812',
    projectId: 'smarttask-baff9',
    storageBucket: 'smarttask-baff9.firebasestorage.app',
    iosBundleId: 'com.smarttask.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBROrJliuIDbOHbsFSc8hhCrbkNYavLfxE',
    authDomain: 'smarttask-baff9.firebaseapp.com',
    projectId: 'smarttask-baff9',
    storageBucket: 'smarttask-baff9.firebasestorage.app',
    messagingSenderId: '511982273812',
    appId: '1:511982273812:web:08d6bdf203bd8284386e01',
    measurementId: 'G-XEZBJ2XS78',
  );
}
